# Generated by Django 3.1.7 on 2021-03-31 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('crsid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('register_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Staircase',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qrdb.building')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('floor', models.CharField(max_length=1)),
                ('view', models.CharField(blank=True, max_length=20)),
                ('room_type', models.CharField(blank=True, max_length=25)),
                ('bathroom', models.CharField(blank=True, max_length=25)),
                ('staircase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qrdb.staircase')),
            ],
        ),
        migrations.CreateModel(
            name='Review_v1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crsid', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
                ('storage', models.IntegerField()),
                ('size', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('kitchen', models.IntegerField()),
                ('noise', models.IntegerField()),
                ('comments', models.TextField(blank=True)),
                ('rentcomment', models.TextField(blank=True)),
                ('rent_vary', models.IntegerField()),
                ('light', models.IntegerField()),
                ('furniture', models.IntegerField()),
                ('moderated', models.BooleanField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qrdb.room')),
            ],
            options={
                'unique_together': {('crsid', 'room')},
            },
        ),
    ]
