# Generated by Django 3.1.7 on 2021-03-31 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrdb', '0002_auto_20210331_1613'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review_v1',
            unique_together=set(),
        ),
    ]
