# Generated by Django 3.1.7 on 2021-06-21 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qrdb', '0003_auto_20210331_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review_v2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crsid', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=20)),
                ('hash_id', models.CharField(max_length=100)),
                ('room_rating_overall', models.IntegerField()),
                ('room_rating_light', models.IntegerField()),
                ('room_rating_view', models.IntegerField()),
                ('room_rating_quiet', models.IntegerField()),
                ('room_rating_size', models.IntegerField()),
                ('room_rating_storage', models.IntegerField()),
                ('room_rating_bathroom', models.IntegerField()),
                ('room_rating_heating', models.IntegerField()),
                ('room_rating_repair', models.IntegerField()),
                ('room_rating_furniture', models.IntegerField()),
                ('room_rating_gyp', models.IntegerField()),
                ('room_rating_wifi', models.IntegerField()),
                ('bathroom_sharing', models.IntegerField(blank=True)),
                ('gyp_sharing', models.IntegerField(blank=True)),
                ('room_tips', models.TextField(blank=True)),
                ('room_review', models.TextField(blank=True)),
                ('room_feedback', models.TextField(blank=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qrdb.room')),
            ],
            options={
                'unique_together': {('crsid', 'room', 'year')},
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField(max_length=256000)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qrdb.review_v2')),
            ],
        ),
    ]
